Bump sonata-project/datagrid-bundle to version ^3.0
sonata-project/SonataUserBundle pull request #1230
Opened 2020-09-22 21:41 UTC by wbloszyk

## Subject

I am targeting this branch, because we should bump in this branch. It is potential BC-break.

## Changelog

```markdown
### Added
- support for sonata-project/datagrid-bundle to version ^3.0
### Removed
- support for sonata-project/datagrid-bundle to version < 3.0
```

2020-09-23 07:50 UTC, VincentLanglet commented on UPGRADE-4.x.md
> +UPGRADE FROM 3.x to 3.x
UPGRADE FROM 4.x to 4.x

2020-09-23 07:57 UTC, wbloszyk commented on UPGRADE-4.x.md
> +UPGRADE FROM 3.x to 3.x
Copy/Paste bug :smile:

2020-09-23 07:58 UTC, wbloszyk commented on UPGRADE-4.x.md
> +UPGRADE FROM 3.x to 3.x
Fixed.

2020-09-23 08:00 UTC, VincentLanglet approved these changes

2020-09-23 08:00 UTC, VincentLanglet commented
Test are failing

2020-09-23 08:09 UTC, wbloszyk commented
@VincentLanglet Test are failing becouse API. The will be fix in #1225.

2020-09-23 12:44 UTC, phansys requested changes

2020-09-23 12:44 UTC, phansys commented on UPGRADE-4.x.md
> +If you are extending these method you should add parameter and return type hints:
```suggestion
If you are extending these method you MUST add argument and return type declarations:
```

2020-09-23 12:44 UTC, phansys commented on UPGRADE-4.x.md
> +- `Sonata\UserBundle\Entity\UserManager::getPager`
```suggestion
- `Sonata\UserBundle\Entity\UserManager::getPager()`
```

2020-09-23 12:44 UTC, phansys commented on UPGRADE-4.x.md
> +- `Sonata\UserBundle\Entity\GroupManager::getPager`
```suggestion
- `Sonata\UserBundle\Entity\GroupManager::getPager()`
```

2020-09-23 12:44 UTC, phansys commented on tests/Controller/Api/UserControllerTest.php
> +        $pager = $this->createMock(PagerInterface::class);
```suggestion
        $pager = $this->createStub(PagerInterface::class);
```

2020-09-23 12:44 UTC, phansys commented on tests/Controller/Api/UserControllerTest.php
> +        $user = $this->createMock(UserInterface::class);
```suggestion
        $user = $this->createStub(UserInterface::class);
```

2020-09-23 12:44 UTC, phansys commented on tests/Controller/Api/GroupControllerTest.php
> +        $pager = $this->createMock(PagerInterface::class);
```suggestion
        $pager = $this->createStub(PagerInterface::class);
```

2020-09-23 12:50 UTC, phansys commented on UPGRADE-4.x.md
> +
With this approach, we should later group also the required changes for "nelmio/api-doc-bundle" in this section.
IMO, we should stop using bundle aliases (like "SonataDatagridBundle") in order to be specific about the package names.
```suggestion
### Dependencies

 - "sonata-project/datagrid-bundle" is bumped from ^2.4 to ^3.0.
```

2020-09-23 12:55 UTC, phansys commented on UPGRADE-4.x.md
> + - "sonata-project/datagrid-bundle" is bumped from ^2.4 to ^3.0.
Just to give more context to my previous suggestion about this change. I'm proposing something like:
```md
### Dependencies

- "sonata-project/datagrid-bundle" is bumped from ^2.4 to ^3.0.
  Some description about the upgrade process for this dependency
  with all the required information.

- "package/a" is bumped from ^1.0 to ^2.0.
  Some description about the upgrade process for this dependency
  with all the required information.
```

2020-09-23 17:19 UTC, phansys commented on UPGRADE-4.x.md
> +- "nelmio/api-doc-bundle" from now is also supported for ^3.6
The term "now" is relative in a document like this. IMO, we should avoid to make use of these kind of references. The relevant concept here is the version number.
```suggestion
- Added support for "nelmio/api-doc-bundle" ^3.6
```

2020-09-23 18:17 UTC, phansys requested changes

2020-09-23 18:17 UTC, phansys commented on UPGRADE-4.x.md
> +- "sonata-project/datagrid-bundle" is bumped from ^2.4 to ^3.0.
![image](https://user-images.githubusercontent.com/1231441/94052683-a8b8aa00-fdaf-11ea-9e45-63502792a446.png)
```suggestion
- "sonata-project/datagrid-bundle" is bumped from ^2.4 to ^3.0.

```

2020-09-23 18:17 UTC, phansys commented on UPGRADE-4.x.md
> +If you are extending these method you MUST add argument and return type declarations:
```suggestion
  If you are extending these method you MUST add argument and return type declarations:
```

2020-09-23 18:39 UTC, phansys approved these changes

2020-09-24 14:25 UTC, VincentLanglet approved these changes

2020-09-24 21:56 UTC, wbloszyk commented
@phansys Can you re-check it?

2020-09-24 22:35 UTC, phansys approved these changes

2020-09-24 22:35 UTC, phansys commented on UPGRADE-4.x.md
> +  If you are extending these method you MUST add argument and return type declarations:
```suggestion
  If you are extending these methods, you MUST add argument and return type declarations:
```

2020-09-24 22:52 UTC, VincentLanglet approved these changes

2020-09-24 22:53 UTC, phansys approved these changes

2020-09-25 07:42 UTC, merged

2020-09-25 07:43 UTC, VincentLanglet commented
Thanks