Make SonataAdminBundle dependency optional
sonata-project/SonataUserBundle pull request #1503
Opened 2022-02-16 16:53 UTC by supersmile2009

## Subject

This PR makes SonataAdminBundle dependency optional.

I am targeting 5.x branch, because v5 hasn't got to a final release yet and BC breaks can potentially be still accepted and there were no objections to that in the referenced issue.

Closes #1499

## Changelog

```markdown
### Changed
- SonataAdminBundle dependency is now optional. Trying to access `sonata_user.userAdmin` variable in Twig templates will throw a `\LogicException` if SonataAdminBundle is not installed.
```

## To do

- [x] Update the documentation;
- [x] Update the tests;
- [x] Add an upgrade note.

## Notes:
1. Do you think nullable admin Pool in `GlobalVariables` is OK or it would be better to conditionally register pool as another Twig variable (e. g. `sonata_user_admin`)?
2. I've checked the Media and Classification bundles (referenced in the linked issue as bundles with optional Admin dependency) and there seems to be no full-blown integration tests with running separate test-suits with and without Admin. So I took a modest approach with simply unit-testing the extension with a different config.

2022-02-16 20:34 UTC, supersmile2009 commented
Failing tests are not caused by the changes in this PR. See https://github.com/sonata-project/SonataUserBundle/pull/1504

2022-02-16 22:22 UTC, supersmile2009 commented
Disregard my last comment. It appears that some Symfony FrameworkBundle configs are cleverly applied depending on whether a certain dependency is expected to be available in non-dev install. I had to add `framework.assets` config to force activate AssetExtension for twig. Otherwise FrameworkBundle de-registers the service, because `symfony/asset` is not a prod dependency anymore (unlike it was before as a dependency of the admin bundle)

2022-02-17 00:23 UTC, VincentLanglet requested changes

2022-02-17 00:23 UTC, VincentLanglet commented on composer.json
> +        "sonata-project/admin-bundle": "^4.8",
We need to add a line in the conflict 
```
"conflict": {
        "sonata-project/admin-bundle": "<4.8",
        "sonata-project/block-bundle": "<4.0",
        "sonata-project/doctrine-orm-admin-bundle": "<4.0"
    },
```

2022-02-17 13:00 UTC, supersmile2009 commented on composer.json
> +        "sonata-project/admin-bundle": "^4.8",
done

2022-02-17 13:01 UTC, VincentLanglet approved these changes

2022-02-17 13:45 UTC, jordisala1991 approved these changes

2022-02-17 13:45 UTC, merged

2022-02-17 13:45 UTC, jordisala1991 commented
Thanks @supersmile2009 !